[field1]
name = "field1"
engine = "NATIVE_SERIAL"
fieldType = "Normal"
physicalVarNames = ["u", "p"]
spaceCompo = [2, 1]
# space component, the default value is 1
# for scalar fields you can omit this
# for vector fields you must specify this value

[field1.u]
fedofName = "space"
# fedofName contains the name of the subtable which
# contains the fedof data for this field.

[field1.u.space]
baseContinuity = "H1"
baseInterpolation = "Lagrange"
ipType = "Equidistance"
order = 2
spaceCompo = 2

[field1.u.analytical]
name = "exactVel"
returnType = "Scalar"
argType = "SpaceTime"
numArgs = 2
numReturns = 1
luaScript = "./functions.lua"
luaFunctionName = "referenceVel"
plotWithResult = false
plotErrorNorm = false
errorNorm = false
normType = "L2BO"

[field1.p]
fedofName = "space"

[field1.p.space]
baseContinuity = "H1"
baseInterpolation = "Lagrange"
ipType = "Equidistance"
order = 1
spaceCompo = 1
