[solid]
name = "solid"
stressStrainModel = "linearElasticModel"
propNames = ["massDensity", "poissonRatio", "youngsModulus"]

[solid.linearElasticModel]
name = "linearElasticModel"
elasticityType = "ISO"
poissonRatio = 0.1
youngsModulus = 1.0

[solid.massDensity]
name = "massDensity"
returnType = "Scalar"
argType = "Constant"
value = 1.0

[solid.poissonRatio]
name = "poissonRatio"
returnType = "Scalar"
argType = "Constant"
value = 2.0

[solid.youngsModulus]
name = "youngsModulus"
returnType = "Scalar"
argType = "Constant"
value = 3.0
